### ISSUE TITLE
UI for MetaCom

### ISSUE THREAD

**Issue by lidaamber** [metarhia/metacom-android#1]
UI for the first version of MetaCom will be created according to the referenced mock (see https://github.com/metarhia/Metarhia/issues/9#issuecomment-301899303). @MariaKokshaikina do you think we need to create app design in Sketch or apps like that or should we skip this step and start creating layouts for application in .XML? I guess, second way is possible as the first app version functionality requires very simple UI.

**Comment by MariaKokshaikina** [comment]
@lidaamber I think the project on the ninjamock will be enough for us. 
And I'm going to start creating layouts today or tomorrow.
