### ISSUE TITLE
Move dialog controls upper

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacom-android#6]
Sometimes onscreen keyboard overlaps connect button and/or input controls. I'll attach screenshots below. Same problem in chat rook creation dialog.

**Comment by tshemsedinov** [comment]
![1505418694350](https://user-images.githubusercontent.com/4405297/30453073-4f74a76c-99a0-11e7-9249-978b4dfee5ec.png)
![1505418663424](https://user-images.githubusercontent.com/4405297/30453071-4f72a124-99a0-11e7-9fef-70b9b73314f3.png)
![screenshot_20170914-221238](https://user-images.githubusercontent.com/4405297/30453074-4f74c6de-99a0-11e7-8c77-5f8ee6c1c63d.png)

**Comment by lidaamber** [comment]
@tshemsedinov do you want the editable fields to scroll up when the keyboard is open?

**Comment by MariaKokshaikina** [comment]
Fixed for portrait mode
