### ISSUE TITLE
Save host:port locally

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacom-android#7]
I do not know do we save `host:port` in latest version but latest version in googleplay doesn't save it. @lidaamber maybe it's already implemented, so close this issue if so.

**Comment by GYFK** [comment]
@tshemsedinov Implemented.

**Comment by lidaamber** [comment]
It's already implemented in 82e4413cc0cf9e4cba6f1d2e48312671674994df and caa19df75936dba7b0be61812864e0da5ca0a488

**Comment by tshemsedinov** [comment]
@lidaamber current implementation uses stored dictionary of all successfully used passwords, right? That's great and much better then I thought. But after exit and back to login screen again could we use last successfully used passwords already entered in input boxes? (no need to enter first letter and select from the list, just click connect button) ? Together with dictionary it will be best solution for user, I suppose.

**Comment by lidaamber** [comment]
@tshemsedinov do you mean storing last entered host/port pair during one session (until the application gets turned off) or during whole application usage?

**Comment by tshemsedinov** [comment]
@lidaamber whole usage, it should appear after restarting, by default, to minimize operations needed to start app and use. I think we can even automatically connect to latest server. We can showing connection screen with entered latest host:port just after manual "Leave server".

**Comment by lidaamber** [comment]
@tshemsedinov ok
@MariaKokshaikina could you store last entered host/port pair and connect to the last host/port automatically when application starts? And could you fill host and port fields with this pair values in ConnectionFragment, please?

**Comment by MariaKokshaikina** [comment]
@lidaamber ok

**Comment by candy9999** [comment]
Was put on my phone without permission I need it taken off
