### ISSUE TITLE
Black color scheme

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacom-android#8]
We need to have most similar color scheme for Android and iOS. So if iOS switched to black we also should use this scheme.

@GYFK please publish here screenshots of iOS app so Android developers and I can see them and compare with Android color scheme.

@lidaamber please pick RGB color of gray panels in iOS app to use the same color for Android.

**Comment by tshemsedinov** [comment]
Also see this: https://github.com/metarhia/metacom-ios/issues/14

**Comment by lidaamber** [comment]
@tshemsedinov agree with that. We already have screenshots of iOS application with dark theme. I prefer returning to initial dark scheme used in Android, only a bit modified to look more like iOS. @MariaKokshaikina could you check iOS dark theme again and add changes to Android app theme, please?
