### ISSUE TITLE
Hide keyboard

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacom-android#9]
Reproduce: select `chat` tab, select `chat name` input, so keyboard will be shown, then switch to `files` tab.
Now (see image below): we have half-hidden buttons and keyboard associated with hidden input control:
![photo5321187660968077316](https://user-images.githubusercontent.com/4405297/30464957-41101b2e-99dd-11e7-8267-ae09c1ec961f.jpg)

**Comment by lidaamber** [comment]
@tshemsedinov that's ok for Android keyboard behavior, but we can force hide keyboard when switching between tabs, if you want.

**Comment by tshemsedinov** [comment]
That is not my whim, I just draw attention to strange behavior, please just implement with the thought that users will use it everyday, to minimize inconvenience and operations here and in other places. Try to use it and optimize it for yourself.

**Comment by lidaamber** [comment]
@tshemsedinov ok
@MariaKokshaikina could you do that, please?

**Comment by MariaKokshaikina** [comment]
@lidaamber ok
